config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: "messages#create"
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, except: [:new] 
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: {minimum: 3, maximum: 15}, uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user
    def index
        @message = Message.new
        @messages = Message.all
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :require_user

    def create
        message = current_user.messages.build(message_params)
        if message.save
        #ActionCable.server.broadcast "chatroom_channel", foo: message.body
        ActionCable.server.broadcast("chatroom_channel", { content: message_render(message) })
        end
    end


    private
    def message_params
        params.require(:message).permit(:body)
    end
    
    #this mehod renders the message partial  via controller and give the message object to partial through :locals
    def message_render(message)
        render(partial: 'message',locals: {message: message})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            flash[:notice] = "you have successfully signed up"
            redirect_to root_path
        else
            render 'new'
        end
    end


    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

    def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<h3 class="ui center aligned icon header">
  <i class="circular orange coffee icon"></i>
  Friends
</h3>

<div class = "ui two column grid">
 
    <div class = "twelve wide column">
        <div class = "ui fluid raised card chatbox">
            <div class = "content">
                <div class="ui large feed" id="message-container">
                    <%# rendering message partial with @message instance variable %>
                    <%= render @messages %>
                </div>
            </div>
            <div class = "extra content">
                <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true )do |f| %>
                    <div class="field">
                        <div class="ui fluid icon input">
                        <%= f.text_field :body %>
                        <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
                        </div>
                    </div>
                <%end%>
            </div>
        </div>
    </div>

<div class = "four wide column">
    <div class = "ui fluid raised card chatbox">
        <div class = "content">
            <div class="ui inverted vertical menu">
                <a class="active item">
                    Home
                </a>
                <a class="item">
                    Messages
                </a>
                <a class="item">
                    Friends
                </a>
            </div>
        </div>
    </div>
</div>


</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
   <div class="ui <%= message_type %> message">
      <%= message_content %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui large inverted menu">
    <div class = "ui container">
        <%= link_to 'Chatroom', root_path,class: "item" %>
        <a class="item">
            Messages
        </a>
        <div class="right menu">
           <% if logged_in? %>
               <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
            <%else%>
            
                <%= link_to 'LogIn', login_path, class: "ui primary button" %>
            
            <%end%>
            <% if !logged_in? %>
                <%= link_to 'signup', signup_path, class: "ui primary button" %>
            <%end%>

        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class = "ui container">
    <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="ui placeholder segment container">
  <div class="">
    <div class="column">
      <%= form_with(model: @user, html: {class: "ui form", role: "form"}, url: signup_path) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Login", class: "ui orange submit button" %>
      <% end %>
    </div>